//! Static help text. Each method's page shows this intro, then every
//! technique's rule and a freshly generated worked example (see ui/help.rs).

use crate::methods::Method;

pub const OVERVIEW: &[&str] = &[
    "Mental math trainer for quant interviews.",
    "",
    "MODES",
    "  Unlimited practice: endless problems with live streak and accuracy. Esc ends the run.",
    "  Timed practice: score as many as you can before the clock runs out; bests are saved.",
    "  Every wrong or skipped problem shows the full worked solution for its technique.",
    "",
    "IN A SESSION",
    "  0-9 . - /   type the answer (fractions like 3/8 are accepted)",
    "  Enter       submit",
    "  Tab         skip and see the worked solution",
    "  ?           show the rule for the current technique",
    "  Esc         end the session",
    "  Flash anzan only:  [ slower   ] faster   r replay   s toggle the soroban",
    "",
    "DIFFICULTY (1-5)",
    "  Scales the number of digits, how far numbers sit from a base, and how many",
    "  numbers are flashed. Estimation drills also get a tighter tolerance.",
    "",
    "ON THIS SCREEN",
    "  ↑/↓ choose a page   PgUp/PgDn or j/k scroll   ←/→ example difficulty",
    "  n new examples   p practise this method   Esc back",
    "",
    "Stats are saved to your data directory (override with MENTALMATH_DATA_DIR).",
];

pub fn intro(m: Method) -> &'static [&'static str] {
    match m {
        Method::Trachtenberg => &[
            "The Trachtenberg system replaces multiplication tables with one rule per multiplier.",
            "You produce the answer one digit at a time, right to left, and only ever look at a",
            "digit and its right-hand neighbour. Always put a 0 in front of the number: the",
            "leading 0 produces the answer's first digit.",
            "",
            "Worked example: 3,142 × 6. Rule: digit + half the neighbour, +5 if the digit is odd.",
            "  Write 03142.",
            "  2 (neighbour none=0): 2 + 0 = 2                        → write 2",
            "  4 (neighbour 2):      4 + 1 = 5                        → write 5",
            "  1 (neighbour 4):      1 + 2 + 5 (odd) = 8              → write 8",
            "  3 (neighbour 1):      3 + 0 + 5 (odd) = 8              → write 8",
            "  0 (neighbour 3):      0 + 1 = 1                        → write 1",
            "  Answer: 18,852.",
            "",
            "The 'subtract' rules (×9, ×8, ×4, ×3) treat the rightmost digit, the middle digits",
            "and the leading 0 differently. Carries can be larger than 1 (×8 and ×3 double).",
        ],
        Method::Cross => &[
            "Vertically and crosswise: build the product one column at a time instead of writing",
            "partial products. Column k collects every digit pair whose place values add to k.",
            "",
            "Worked example: 64 × 37.",
            "  Units:    4×7 = 28                      → write 8, carry 2",
            "  Tens:     6×7 + 4×3 = 42 + 12 = 54, +2 = 56 → write 6, carry 5",
            "  Hundreds: 6×3 = 18, +5 = 23             → write 23",
            "  Answer: 2,368.",
            "",
            "For 3-digit numbers the middle column has three cross products (a·f + b·e + c·d).",
            "Keep only the running carry in your head: it's the one thing you must not drop.",
        ],
        Method::Anzan => &[
            "Anzan is calculating on an imagined soroban. Flash anzan shows numbers one at a time;",
            "you update the picture after each one and never hold more than the running total.",
            "",
            "A soroban rod has one heaven bead (5) and four earth beads (1 each). A bead counts",
            "when it's pushed to the beam. Adding with too few beads uses complements:",
            "  5-complement:  +4 when the rod shows 3 → lower heaven (+5), drop 1 earth (−1).",
            "  10-complement: +8 when the rod shows 7 → remove 2 on this rod, +1 on the tens rod.",
            "",
            "Worked example: flash 7, 8, 4, 6.",
            "  Set 7              heaven down, 2 earth up",
            "  7 + 8 = 15         10-complement: −2 on units (drop 2 earth), +1 on tens",
            "  15 + 4 = 19        raise 4 earth (direct)",
            "  19 + 6 = 25        10-complement: −4 on units (drop 4 earth), +1 on tens",
            "  Total = 25",
            "",
            "Use the Soroban visualizer from the main menu to practise seeing numbers as beads.",
        ],
        Method::Vedic => &[
            "Base methods: pick a nearby round number (a base), work with the small deviations,",
            "and fix up at the end. They turn large multiplications into one small one.",
            "",
            "Worked example: 97 × 94 near base 100.",
            "  Deviations: 97 → −3, 94 → −6.",
            "  Cross-add: 97 − 6 = 91 (or 94 − 3) → 9100.",
            "  Multiply deviations: (−3)(−6) = 18.",
            "  Answer: 9,118.",
            "",
            "If one number is above the base and one below, the deviation product is negative:",
            "  103 × 96: 103 − 4 = 99 → 9900; (+3)(−4) = −12 → 9,888.",
        ],
        Method::Quant => &[
            "The arithmetic that shows up in trading interviews: converting fractions, quick",
            "percentages, estimating to within a couple of percent, and expected values.",
            "",
            "Worked example: estimate 7,431 ÷ 23 to within 2%.",
            "  Round the divisor: 23 ≈ 20.",
            "  7,431 ÷ 20 = 371.55 (15% too high, since 20 is 13% smaller than 23).",
            "  Scale by 20/23 ≈ 1 − 0.13 → about 323.",
            "  Exact: 323.09. Within 2% means anything from about 316.6 to 329.6.",
            "",
            "Estimation problems accept any answer inside the stated tolerance.",
        ],
    }
}
